### ISSUE TITLE
Error "This script should not be run as root"

### ISSUE THREAD

**Issue by bigwave** [R0GGER/docker-wsusoffline#1]
I'm running this using the docker plugin for Open Media Vault (http://www.openmediavault.org/) and get a "This script should not be run as root" error.

What further debugging information would be helpful?

**Comment by R0GGER** [comment]
Yup I know... Thanks for reporting.
When I have time I will rewrite the script.

**Comment by bigwave** [comment]
@hot22shot you could try the fork that I've made it "works for me" but it's my first foray into docker containers so YMMV.

**Comment by hot22shot** [comment]
Tried it, but it doesn't work well with my system (docker on a Synology DS916+).

**Comment by R0GGER** [comment]
Problem solved. Credits to @bigwave !
Thanks!
