### ISSUE TITLE
Download Office Updates fails with error code 1

### ISSUE THREAD

**Issue by hot22shot** [R0GGER/docker-wsusoffline#2]
Hello,

I tested the docker for the following tasks : 
- download windows 10 updates
- download office 2016 updates
- for enu and fra languages

Following your recent commits Windows 10 updates are fine, but office 2016 fails : 
./download-updates-tasks/10-parse-command-line.bash: line 331: architectures_list[*]: unbound variable
Exiting with error code 1  (temporary files are kept for debugging)...

Here's the complete log extract : 

Info: Starting download-updates.bash 1.1 (2018-02-06)

Info: Command line: ./download-updates.bash o2k16-x64 enu,fra

Info: Running on WSUS Offline Update version 11.2.2

Info: Repository last updated on 2018-04-20

Info: Checking needed applications...

Info: Checking recommended applications...

Info: Found Linux trash handler: trash-put

Info: Setting download options for GNU Wget...

Info: Wake up sleeping DSL modems and routers...

PING fg.download.windowsupdate.com.c.footprint.net (8.248.103.254) 56(84) bytes of data.

--- fg.download.windowsupdate.com.c.footprint.net ping statistics ---

4 packets transmitted, 0 received, 100% packet loss, time 2999ms

Info: Testing the Internet connection...

Info: Connection test succeeded

Info: Skipped searching for new versions of WSUS Offline Update, because it has 

already been done less than one day ago

Info: Skipped update of configuration files for WSUS Offline Update, because it 

has already been done less than one day ago

Info: Parsing command-line...

Info: Parsing first parameter...

Info: Adding "o2k16-x64" to the list of updates...

Info: Parsing preliminary list of updates...

Info: Found update: o2k16-x64, Office 2016, 32-bit and 64-bit

Info: Adding common updates for all Windows and Office versions...

Info: Adding "ofc" to the list of updates...

Info: Building a list of needed architectures for the included downloads. This 

depends on Windows updates only...

Info: Parsing second parameter...

Info: Found language: enu, en, English

Info: Found language: fra, fr, French

Info: Parsing remaining parameters...

./download-updates-tasks/10-parse-command-line.bash: line 331: architectures_list[*]: unbound variable

Exiting with error code 1  (temporary files are kept for debugging)...

Sleeping for 48h before next download.

Apr 20 12:45:42 wsusoffline syslog-ng[12]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'_

**Comment by R0GGER** [comment]
> ./download-updates-tasks/10-parse-command-line.bash: line 331: architectures_list[*]: unbound variable
> Exiting with error code 1 (temporary files are kept for debugging)...
Please report this issue at http://forums.wsusoffline.net.

**Comment by hot22shot** [comment]
Will do !

**Comment by R0GGER** [comment]
Issue fixed in WSUS Offline Update 11.4.
