### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by Novaal** [R0GGER/docker-wsusoffline#3]
Hi @R0GGER, 

thanks for providing a docker image for wsusoffline.
I have some feedback for this docker image. I hope it is appreciated.

1. Include the installed Version into the image and use Git and Docker-Tags for Versioning instead of always installing the newest version on start. This should speedup the starting process a little bit and it allows to use an old Version of wsusofffline, if needed. Git and Docker Tags could be the same like the release Versions. This could be automated with some CI/CD-Environment, like CircleCI or Jenkins.
2. Do not use multiple `RUN` Commands to install and cleanup dependencies [here](https://github.com/R0GGER/docker-wsusoffline/blob/ec8f98fa4aa4fa9733f20c437831cb0e93963a1d/Dockerfile#L5). This will create multiple intermediate image layers (more infos for example [here](https://stackoverflow.com/questions/31222377/what-are-docker-image-layers) or [here](https://stackoverflow.com/questions/39223249/multiple-run-vs-single-chained-run-in-dockerfile-what-is-better)). Instead call them all in one time, so that this will produce only one intermediate layer.
3. Add an option to run the Docker Container only once, like `EXIT=true` or `ONCE=true`. This would disable also the `SLEEP`-Setting.

**Comment by R0GGER** [comment]
Thanks for your feedback! Much appreciated ;) 
When I have time I will try to change a few things you suggested.

**Comment by R0GGER** [comment]
@Brice187 Thanks!
