### ISSUE TITLE
Feature: add timestamp after run

### ISSUE THREAD

**Issue by rliegmann** [R0GGER/docker-wsusoffline#5]
Hello,

Thanks for the great work. 

I have the idea to spend the current time at the end of an update run. This one can stand in docker log the current status. 
Like :  Last successfully run at 2019-07-12  15:00

thank you in advance

**Comment by R0GGER** [comment]
Hi rliegmann, 

Sorry for my late reply...
Do you mean log date/time after each successful update run within Windows (installing updates) or after each wsusoffline update run within Docker (downloading updates)?

Can you clarify your feature request?
