### ISSUE TITLE
Can I use this as a WSUS server?

### ISSUE THREAD

**Issue by EriksonBahr** [R0GGER/docker-wsusoffline#6]
I just tried this image and it seems to be working fine (it downloaded several GBs of updates), and now I'm wondering if I can make it my WSUS server (if I proper configure the server in regedit).

I checked the dockerfile and I did not see any expose command, so I don't have any clue of which port I should open nor if that's supported.

Can I use this as a WSUS server?

**Comment by R0GGER** [comment]
> Can I use this as a WSUS server?
No. WSUS Offline Update is not a complete replacement for Online Update or a WSUS Server.
The main goal of WSUS Offline Update is to quickly and safely bring freshly installed Windows systems to a patch level which allows them to be safely connected to the Internet.
